### ISSUE TITLE
Low fps

### ISSUE THREAD

**Issue by dark1umen** [Feiryn/LethalMon#9] opened 2024-07-27 14:13 UTC
Hi, I have fps drops in v0.4 to 2-5 fps from 80-120 when I move my mouse. If I move with wasd it's ok. If i connect gamepad, and use mouse it's ok too.

**Comment by Feiryn** [comment] 2024-07-28 08:29
> Hi, I have fps drops in v0.4 to 2-5 fps from 80-120 when I move my mouse. If I move with wasd it's ok. If i connect gamepad, and use mouse it's ok too.

Hello, thank you for the report.
I heard that some players have this issue but I can't reproduce it on my side.

If you start the game with this mod only, does the problem still appear?
In the case it does not, can you send me your mod list?

Also, I have a potential fix version where I optimized the Unity bundle, maybe you can give it a try
[Feiryn-LethalMon-0.4.0-fix.zip](https://github.com/user-attachments/files/16402653/Feiryn-LethalMon-0.4.0-fix.zip)

**Comment by Feiryn** [comment] 2024-07-28 08:49
Nevermind I found a PC lying around where I can reproduce the issue with this mod only. Will work on that

**Comment by dark1umen** [comment] 2024-07-28 09:44
I had same isue in another game with another mouse. As I know this is due to the mouse frequency rate. Now I use razer viper v2, mb it would help. By the way, frequency rate of most mice is 1000 Hz.

**Comment by Feiryn** [comment] 2024-07-28 09:47
> I had same isue in another game with another mouse. As I know this is due to the mouse frequency rate. Now I use razer viper v2, mb it would help. By the way, frequency rate of most mice is 1000 Hz.

Yes I found the issue, I hooked a wrong Unity event. I thought my function was called only when the settings were changed but it was called each time a device input changed. So imagine a mouse updated hundreds of time per seconds and updating the UI hundreds of time too

**Comment by Feiryn** [comment] 2024-07-28 10:03
Bug fixed in version 0.4.1, already release on github and coming soon on the thunderstore

**Closed by Feiryn** 2024-07-28 10:03 UTC
