### ISSUE TITLE
Upon Exiting Game & Re-Opening Pokemon Dissappear or Swapped

### ISSUE THREAD

**Issue by JoshShareprod** [Feiryn/LethalMon#43] opened 2024-09-13 04:32 UTC
Whenever I close out my game and open the same moon my Pokemon go missing and the Poke balls become empty. Sometimes but it is very rare they are swapped to a different Poke ball with a different captured mob. For example, I had a Butler in my master ball earlier today and I got off for about 1-2 hours. Upon re-launching the game my Butler is gone and I know have a bracken in a great ball that used to be empty. I am un-sure what the cause of this is but it is very irritating to have. Let me know if you need anymore information!

All the best

**Comment by Feiryn** [comment] 2024-09-13 08:54
Hello, thanks for the report. I will investigate and fix this as soon as I can.
I close this issue for being a duplicate of #32

**Closed by Feiryn** 2024-09-13 08:54 UTC
Labels: duplicate
